In [5]:
import numpy as np
array = np.array([101,102,103,104], dtype ='float')

In [6]:
array

array([101., 102., 103., 104.])

In [7]:
type(array)

numpy.ndarray

In [9]:
for i in array:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [10]:
array1 = np.array([101,102,103,104.5,106])

In [11]:
for i in array1:
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [12]:
zeros = np.zeros(5)

In [13]:
zeros 

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
a = np.random.rand(100)

In [28]:
b = np.random.randint(50)

In [31]:
np.random.randn(100)

array([-1.35031666, -2.18060417,  2.51597713, -0.43450081,  0.36521318,
       -0.78264111,  0.80950303,  0.38271899,  0.96909124, -1.93842059,
        2.47795867,  0.53806531, -1.21719481, -1.53811785,  0.18392013,
        1.06170185, -0.7155027 ,  0.43339785,  1.2705969 ,  0.11638145,
        0.28540268,  0.59778314,  0.70591351,  0.03006687,  0.05734811,
       -0.0408667 , -1.37006853, -0.60767031, -0.04198895, -0.01384847,
        2.02391552,  3.0262329 ,  0.47447081, -2.37574837,  0.47370061,
       -1.37697611, -0.2868791 ,  0.84763927,  0.24623452,  0.01942178,
        0.12548116,  0.05228797, -0.4152081 ,  0.24163937,  1.06023174,
        0.73624642, -1.73005058,  0.10378049,  1.10615903,  0.72520096,
        0.72056616,  1.38259764, -0.31592375, -0.35704787,  1.68322283,
        1.01710737, -1.20453386, -0.01883128, -0.57099256,  1.72547341,
       -0.0952548 , -0.08196198,  0.85453362, -0.87076357,  0.23141568,
        1.3127795 , -0.94763653,  1.37616389, -0.53518772,  0.39

In [37]:
#2-D arrays in numpy

x = np.array([[1,2,3,4,5],[6,5,4,7,9],[8,7,2,1,3]])
x

array([[1, 2, 3, 4, 5],
       [6, 5, 4, 7, 9],
       [8, 7, 2, 1, 3]])

In [40]:
x[1][3]

7

In [41]:
x[1][0:3]

array([6, 5, 4])

In [44]:
from numpy import *
y = array([2,34,56,32,54])
z = array([[4, 9, 16, 25], [36, 16, 4, 49]])
 
print(sum(y))

178


In [45]:
print(sum(z))

159


In [48]:
f = [1,2,3,4,5,6]
g = reshape(f,(3,2))

In [49]:
g

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
h = [1,3,4,7,6,42,56,76,4,32,2,3]
i = reshape(h,(3,2,2))


In [54]:
i

array([[[ 1,  3],
        [ 4,  7]],

       [[ 6, 42],
        [56, 76]],

       [[ 4, 32],
        [ 2,  3]]])