In [27]:
# 1D Array using array Function Numpy Example 1
import numpy as np
stu_roll = np.array([101, 102, 103, 104, 105])
print(stu_roll)
print(stu_roll.dtype)
print(stu_roll[0])
print(stu_roll[1])
print(stu_roll[2])
print(stu_roll[3])
print(stu_roll[4])

[101 102 103 104 105]
int32
101
102
103
104
105


In [28]:
# 1D Array with Float Number using array Function Numpy Example 2
stu_roll = np.array([101, 102, 103, 104, 105], dtype=float)
print(stu_roll)
print(stu_roll.dtype)
print(stu_roll[0])
print(stu_roll[1])
print(stu_roll[2])
print(stu_roll[3])
print(stu_roll[4])



[101. 102. 103. 104. 105.]
float64
101.0
102.0
103.0
104.0
105.0


In [29]:
# 1D Array with Implicit Float Conversion using array Function Numpy Example 3
stu_roll = np.array([101, 102, 103, 104, 10.5])
print(stu_roll)
print(stu_roll.dtype)
print(stu_roll[0])
print(stu_roll[1])
print(stu_roll[2])
print(stu_roll[3])
print(stu_roll[4])



[101.  102.  103.  104.   10.5]
float64
101.0
102.0
103.0
104.0
10.5


In [30]:
# 1D Array with Character using array Function Numpy Exmaple 4
stu_roll = np.array(['a', 'b', 'c', 'd', 'e'])
print(stu_roll)
print(stu_roll.dtype)
print(stu_roll[0])
print(stu_roll[1])
print(stu_roll[2])
print(stu_roll[3])
print(stu_roll[4])



['a' 'b' 'c' 'd' 'e']
<U1
a
b
c
d
e


In [31]:
# 1D Array with string using array Function Numpy Example 5
stu_roll = np.array(['Rahul', 'Sonam', 'Raj', 'Rani', 'Sumit'])
print(stu_roll)
print(stu_roll.dtype)
print(stu_roll[0])
print(stu_roll[1])
print(stu_roll[2])
print(stu_roll[3])
print(stu_roll[4])



['Rahul' 'Sonam' 'Raj' 'Rani' 'Sumit']
<U5
Rahul
Sonam
Raj
Rani
Sumit


In [32]:
# 1D Array using array Function Numpy Example 6
from numpy import *
stu_roll = array([101, 102, 103, 104, 105])
print(stu_roll)
print(stu_roll.dtype)
print(stu_roll[0])
print(stu_roll[1])
print(stu_roll[2])
print(stu_roll[3])
print(stu_roll[4])

[101 102 103 104 105]
int32
101
102
103
104
105


In [33]:
# 1D Array using array Function Numpy
from numpy import *
stu_roll = array([101, 102, 103, 104, 105])

for element in stu_roll:
	print(element)

101
102
103
104
105


In [34]:
# 1D Array using array Function Numpy
from numpy import *
stu_roll = array([101, 102, 103, 104, 105])

n = len(stu_roll)
for i in range(n):
	print('index',i,"=",stu_roll[i])

index 0 = 101
index 1 = 102
index 2 = 103
index 3 = 104
index 4 = 105


In [35]:
# Getting Input from User in 1D Array numpy
from numpy import *
n = int(input("Enter Number of Elements: "))
a = zeros(n, dtype=int)
for i in range(len(a)):
	x = int(input("Enter Element: "))
	a[i] = x
for i in range(len(a)):
	print(a[i])


Enter Number of Elements:  3
Enter Element:  1
Enter Element:  2
Enter Element:  3


1
2
3


In [36]:
from numpy import *
a = logspace(1, 3, 5)

print("**** Accessing Individual Elements ****")
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])
print()

print("**** Accessing by For Loop ****")
for el in a:
	print(el)
print()

print("**** Accessing by For Loop with Index ****")	
n = len(a)
for i in range(n):
	print('index',i,'=',a[i])
print()

print("**** Accessing by While Loop ****")	
n = len(a)
i = 0
while i < n:
	print('index',i,'=',a[i])
	i+=1

**** Accessing Individual Elements ****
10.0
31.622776601683793
100.0
316.22776601683796
1000.0

**** Accessing by For Loop ****
10.0
31.622776601683793
100.0
316.22776601683796
1000.0

**** Accessing by For Loop with Index ****
index 0 = 10.0
index 1 = 31.622776601683793
index 2 = 100.0
index 3 = 316.22776601683796
index 4 = 1000.0

**** Accessing by While Loop ****
index 0 = 10.0
index 1 = 31.622776601683793
index 2 = 100.0
index 3 = 316.22776601683796
index 4 = 1000.0


In [37]:
from numpy import *
a = arange(5)
#a = arange(5.0)
#a = arange(1, 6)
#a = arange(1, 10, 2)

print("**** Accessing Individual Elements ****")
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])
print()

print("**** Accessing by For Loop ****")
for el in a:
	print(el)
print()

print("**** Accessing by For Loop with Index ****")	
n = len(a)
for i in range(n):
	print('index',i,'=',a[i])
print()

print("**** Accessing by While Loop ****")	
n = len(a)
i = 0
while i < n:
	print('index',i,'=',a[i])
	i+=1

**** Accessing Individual Elements ****
0
1
2
3
4

**** Accessing by For Loop ****
0
1
2
3
4

**** Accessing by For Loop with Index ****
index 0 = 0
index 1 = 1
index 2 = 2
index 3 = 3
index 4 = 4

**** Accessing by While Loop ****
index 0 = 0
index 1 = 1
index 2 = 2
index 3 = 3
index 4 = 4


In [38]:
# 1D Array using zeros Function Numpy
from numpy import *
a = zeros(5)
#a = zeros(5, dtype=int)

print("**** Accessing Individual Elements ****")
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])
print()

print("**** Accessing by For Loop ****")
for el in a:
	print(el)
print()

print("**** Accessing by For Loop with Index ****")	
n = len(a)
for i in range(n):
	print('index',i,'=',a[i])
print()

print("**** Accessing by While Loop ****")	
n = len(a)
i = 0
while i < n:
	print('index',i,'=',a[i])
	i+=1

**** Accessing Individual Elements ****
0.0
0.0
0.0
0.0
0.0

**** Accessing by For Loop ****
0.0
0.0
0.0
0.0
0.0

**** Accessing by For Loop with Index ****
index 0 = 0.0
index 1 = 0.0
index 2 = 0.0
index 3 = 0.0
index 4 = 0.0

**** Accessing by While Loop ****
index 0 = 0.0
index 1 = 0.0
index 2 = 0.0
index 3 = 0.0
index 4 = 0.0


In [39]:
# 1D Array using ones Function Numpy
from numpy import *
a = ones(5)
#a = ones(5, dtype=int)

print("**** Accessing Individual Elements ****")
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])
print()

print("**** Accessing by For Loop ****")
for el in a:
	print(el)
print()

print("**** Accessing by For Loop with Index ****")	
n = len(a)
for i in range(n):
	print('index',i,'=',a[i])
print()

print("**** Accessing by While Loop ****")	
n = len(a)
i = 0
while i < n:
	print('index',i,'=',a[i])
	i+=1

**** Accessing Individual Elements ****
1.0
1.0
1.0
1.0
1.0

**** Accessing by For Loop ****
1.0
1.0
1.0
1.0
1.0

**** Accessing by For Loop with Index ****
index 0 = 1.0
index 1 = 1.0
index 2 = 1.0
index 3 = 1.0
index 4 = 1.0

**** Accessing by While Loop ****
index 0 = 1.0
index 1 = 1.0
index 2 = 1.0
index 3 = 1.0
index 4 = 1.0


In [40]:
a = array([101, 102, 103, 104, 105])
a = a + 5

for el in a:
	print(el)
print()

106
107
108
109
110



In [41]:
a = array([101, 102, 103, 104, 105])
b = array([1, 2, 3, 4, 5])
c = a + b

for el in c:
	print(el)
print()

102
104
106
108
110



In [42]:
a = array([100, 200, 13, 400, 500])
b = array([100, 20, 30, 400, 50])
result1 = a == b
result2 = a < b
result3 = a > b
result4 = a <= b
result5 = a >= b
result6 = a != b
print("a", a)
print("b", b)
print("a==b",result1)
print("a<b",result2)
print("a>b",result3)
print("a<=b",result4)
print("a>=b",result5)
print("a!b",result6)

a [100 200  13 400 500]
b [100  20  30 400  50]
a==b [ True False False  True False]
a<b [False False  True False False]
a>b [False  True False False  True]
a<=b [ True False  True  True False]
a>=b [ True  True False  True  True]
a!b [False  True  True False  True]


In [43]:
a = array([100, 200, 300, 400, 500])
b = array([100, 20, 30, 400, 50])
result = a == b
print(any(result))
print(all(result))

True
False


In [44]:
a = array([101, 12, 300, 4, 500])
b = array([100, 20, 30, 400, 50])
result = where(a>b, a, b)
print(result)

[101  20 300 400 500]


In [45]:
a = array([100, 200, 13, 0, 400, 500, 0])
result = nonzero(a)
print(result)


(array([0, 1, 2, 4, 5], dtype=int64),)


In [46]:
# 2D Array using Array Function Numpy
import numpy
a = numpy.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(a)
print(a.dtype)
print(a[0][0])
print(a[0][1])
print(a[0][2])
print(a[0][3])
print(a[1][0])
print(a[1][1])
print(a[1][2])
print(a[1][3])

# 2D Array with Float Number using array Function Numpy Example 2
import numpy
a = numpy.array([[10, 20, 30, 40], [50, 60, 70, 80]], dtype=float)
print(a)
print(a.dtype)
print(a[0][0])
print(a[0][1])
print(a[0][2])
print(a[0][3])
print(a[1][0])
print(a[1][1])
print(a[1][2])
print(a[1][3])

# 2D Array with Implicit Float Conversion using array Function Numpy Example 3
import numpy
a = numpy.array([[10, 20, 30, 40], [50, 60, 70, 8.0]])
print(a)
print(a.dtype)
print(a[0][0])
print(a[0][1])
print(a[0][2])
print(a[0][3])
print(a[1][0])
print(a[1][1])
print(a[1][2])
print(a[1][3])

# 2D Array with String using array Function Numpy Exmaple 4
import numpy
a = numpy.array([['Rahul', 'Sonam', 'Raj', 'Rani'], ['Dell', 'Asus', 'Lenovo', 'HP']])
print(a)
print(a.dtype)
print(a[0][0])
print(a[0][1])
print(a[0][2])
print(a[0][3])
print(a[1][0])
print(a[1][1])
print(a[1][2])
print(a[1][3])

# 2D Array using array Function Numpy Example 5
from numpy import *
a = array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(a)
print(a.dtype)
print(a[0][0])
print(a[0][1])
print(a[0][2])
print(a[0][3])
print(a[1][0])
print(a[1][1])
print(a[1][2])
print(a[1][3])

[[10 20 30 40]
 [50 60 70 80]]
int32
10
20
30
40
50
60
70
80
[[10. 20. 30. 40.]
 [50. 60. 70. 80.]]
float64
10.0
20.0
30.0
40.0
50.0
60.0
70.0
80.0
[[10. 20. 30. 40.]
 [50. 60. 70.  8.]]
float64
10.0
20.0
30.0
40.0
50.0
60.0
70.0
8.0
[['Rahul' 'Sonam' 'Raj' 'Rani']
 ['Dell' 'Asus' 'Lenovo' 'HP']]
<U6
Rahul
Sonam
Raj
Rani
Dell
Asus
Lenovo
HP
[[10 20 30 40]
 [50 60 70 80]]
int32
10
20
30
40
50
60
70
80


In [47]:
from numpy import *
a = array([[10, 20, 30, 40], [50, 60, 70, 80]])

for r in a:
	for c in r:
		print(c)
	print()


10
20
30
40

50
60
70
80



In [48]:
from numpy import *
a = array([[10, 20, 30, 40], [50, 60, 70, 80]])

n = len(a)
for i in range(n):
	for j in range(len(a[i])):
		print('index',i,j,"=",a[i][j])
	print()

index 0 0 = 10
index 0 1 = 20
index 0 2 = 30
index 0 3 = 40

index 1 0 = 50
index 1 1 = 60
index 1 2 = 70
index 1 3 = 80



In [49]:
from numpy import *
a = array([[10, 20, 30, 40], [50, 60, 70, 80]])

a[1][2] = 100

n = len(a)
for i in range(n):
    for j in range(len(a[i])):
        print('index',i,j,"=",a[i][j])
    print()


index 0 0 = 10
index 0 1 = 20
index 0 2 = 30
index 0 3 = 40

index 1 0 = 50
index 1 1 = 60
index 1 2 = 100
index 1 3 = 80



In [50]:
a = array([[10, 20, 30, 40], [50, 60, 70, 80]])

n = len(a)
i = 0
while i < n :
	j = 0
	while j < len(a[i]):
		print('index',i,j,"=",a[i][j])
		j+=1
	i+=1
	print()

index 0 0 = 10
index 0 1 = 20
index 0 2 = 30
index 0 3 = 40

index 1 0 = 50
index 1 1 = 60
index 1 2 = 70
index 1 3 = 80



In [51]:
n = array([[10, 20, 30], 
		   [40, 50, 60], 
		   [70, 80, 90]])
print("Original Array")
print(n)

print("0th Row All Columns")	
# 0th Row All Columns
a = n[0, :]
for i in a:
		print(i)

print("1st Row All Columns")
# 1st Row All Columns
b = n[1, :]
for i in b:
		print(i)

print("2nd Row All Columns")
# 2nd Row All Columns
c = n[2, :]
for i in c:
		print(i)

print("0th Column All Rows")
# 0th Column All Rows
d = n[:, 0]
for i in d:
		print(i)

print("1st Column All Rows")
# 1st Column All Rows
e = n[:, 1]
for i in e:
		print(i)

print("2nd Column All Rows")
# 2nd Column All Rows
f = n[:, 2]
for i in f:
		print(i)


print("Element 10, 0th row 0th column")
g = n[0:1, 0:1]
print(g)

print("Element 90, 2nd row 2nd column")
h = n[2:3, 2:3]
print(h)

print("0th row and 1st row of 1st column and 2nd column")
h = n[0:2, 1:3]
print(h)	

Original Array
[[10 20 30]
 [40 50 60]
 [70 80 90]]
0th Row All Columns
10
20
30
1st Row All Columns
40
50
60
2nd Row All Columns
70
80
90
0th Column All Rows
10
40
70
1st Column All Rows
20
50
80
2nd Column All Rows
30
60
90
Element 10, 0th row 0th column
[[10]]
Element 90, 2nd row 2nd column
[[90]]
0th row and 1st row of 1st column and 2nd column
[[20 30]
 [50 60]]


In [ ]:
a = array([25, 81, 49, 64])
b = array([[4, 9, 16, 25], [36, 16, 4, 49]])
print()
#sum() Function
print("a:",sum(a))
print("b:",sum(b))
print()
#prod() Function
print("a:",prod(a))
print("b:",prod(b))
print()
#sqrt() Function
print("a:",sqrt(a))
print("b:",sqrt(b))



a: 219
b: 159

a: 6350400
b: 1625702400

a: [5. 9. 7. 8.]
b: [[2. 3. 4. 5.]
 [6. 4. 2. 7.]]


In [53]:
a = array([1, 2, 3, 4, 5, 6])
b = reshape(a, (2, 3))
print(a)
print(b)
print()

# 1D to 3D
c = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
d = reshape(c, (2, 3, 2))
print(c)
print(d)
print()

#2D to 1D
e = array([[1, 2, 3], [4, 5, 6]])
f = reshape(e, (6))
print(e)
print(f)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [54]:
e = array([[1, 2, 3], [4, 5, 6]])
f = e.flatten()
print(e)
print(f)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [55]:
a = array([101, 102, 103, 104, 105])
b = array([[10, 20, 30, 40], [50, 60, 70, 80]])
print()
# ndim Attribute
print("1D Array ndim:",a.ndim)
print("2D Array ndim:",b.ndim)
print()
#shape Attribute 
#For 1D array shape elements in the row
#For 2D array shape specifies number of row and column in each row
print("1D Array shape:",a.shape)
print("2D Array shape:",b.shape)
#size Attribute
print("1D Array size:",a.size)
print("2D Array size:",b.size)
#itemsize Attribute
print("1D Array itemsize:",a.itemsize)
print("2D Array itemsize:",b.itemsize)
#dtype Attribute
print("1D Array dtype:",a.dtype)
print("2D Array dtype:",b.dtype)
#nbytes Attribute
print("1D Array nbytes:",a.nbytes)
print("2D Array nbytes:",b.nbytes)
print()


1D Array ndim: 1
2D Array ndim: 2

1D Array shape: (5,)
2D Array shape: (2, 4)
1D Array size: 5
2D Array size: 8
1D Array itemsize: 4
2D Array itemsize: 4
1D Array dtype: int32
2D Array dtype: int32
1D Array nbytes: 20
2D Array nbytes: 32

